[mod]
id = "necromancer"
name = "Necromancer"
version = "0.1.0"

[[entities]]
type = "summoner"
sprite = "sprites/summoner_atlas"
pivot = [49.0, 2.0]
health = 100
energy = 100
speed = 1

[[entities]]
type = "skeleton"
sprite = "sprites/skeleton_atlas"
pivot = [24.0, 0.0]
health = 50
energy = 50
speed = 2

[[entities]]
type = "merchant"
sprite = "sprites/merchant_atlas"
pivot = [24.0, 0.0]
health = 80
energy = 80
speed = 1

[[spawn]]
entity_type = "summoner"
name = "summoner"
position = 500

[commands]
initial = ["consult", "raise", "harvest", "pact"]
